sonar.projectKey=tenproduct_aiohttp-jwt
sonar.organization=tengroup
sonar.host.url=https://sonarcloud.io

# Path to sources
sonar.sources=.
sonar.inclusions=**/*.py

# Path to tests
sonar.test.inclusions=**/tests/**, **/test_**.py

# Exclusions
sonar.exclusions=**/tests/**,**/__pycache__/**,**/fixtures/**,ci/**,coverage/**,coverage.xml

# Coverage report
sonar.python.coverage.reportPaths=coverage.xml
sonar.coverage.exclusions=**/tests/**,**/conftest.py,**/__pycache__/**,**/fixtures/**,ci/**,**/setup.py

# Python specific settings
sonar.python.version=3.10

# Source encoding
sonar.sourceEncoding=UTF-8
sonar.scm.provider=git
